name: dotnet package

on:
    # Trigger the workflow on push or pull request,
    # but only for the main branch
    push:
        branches:
            - main
        paths:
            - 'src/BibServices/**'
    pull_request:
        branches:
            - main
        paths:
            - 'src/BibServices/**'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: '6.0.x'
                  include-prerelease: true
            - name: Install dependencies
              working-directory: ./src/BibServices/Bibs.API/
              run: dotnet restore
            - name: Build
              working-directory: ./src/BibServices/Bibs.API/
              run: dotnet build --configuration Release --no-restore
            - name: Test
              working-directory: ./src/BibServices/Bibs.API/
              run: dotnet test --no-restore --verbosity normal
