name: docker image build

on:
    # Trigger the workflow on push or pull request,
    # but only for the main branch
    push:
        # branches:
        #     - main
        #     - ••/••
        paths:
            - 'src/BibServices/**'
    pull_request:
        branches:
            - main
        paths:
            - 'src/BibServices/**'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        environment: Production
        defaults:
            run:
                working-directory: ./src/BibServices/
        steps:
            - uses: actions/checkout@v2
            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag git_docker:$(date +%s)

            - name: 'Docker Login'
              uses: azure/docker-login@v1
              with:
                login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
                username: ${{ secrets.REGISTRY_USERNAME }}
                password: ${{ secrets.REGISTRY_PASSWORD }}
 
            - name: Build the frontend image and push it to ACR
              uses: docker/build-push-action@v2
              with:
                push: true
                tags: ${{secrets.REGISTRY_LOGIN_SERVER}}/bibsample:${{ github.sha }}
                file: src/BibServices/Dockerfile