name: docker image build

on:
    # Trigger the workflow on push or pull request,
    # but only for the main branch
    push:
        # branches:
        #     - main
        paths:
            - 'src/BibServices/**'
    pull_request:
        branches:
            - main
        paths:
            - 'src/BibServices/**'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        environment: Production
        defaults:
            run:
                working-directory: ./src/BibServices/
        steps:
            - uses: actions/checkout@v2

            - name: Docker Login to ACR and Push
              uses: azure/docker-login@v1
              with:
                login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
                username: ${{ secrets.REGISTRY_USERNAME }}
                password: ${{ secrets.REGISTRY_PASSWORD }}
            - run: |
                docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/appdb:${{ github.sha }}
                docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/appdb:${{ github.sha }}
